_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 1
                - 2
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.0
            "6": 4.47.1
            "8":
                - 1
                - 5
            "12": 0.19.0
            "13": linux-x86_64
